### ISSUE TITLE
Score Bug

### ISSUE THREAD

**Issue by TheArzhel** [ch0m5/Project_1#1]
# Issue Template

## Summary
Score for player 2 does not work correctly

## Type of Bug 

Select the type of bug with and "x" ([x])

* [ ] Art 
* [ ] Animation 
* [ ] Audio 
* [ ] Particles
* [ ] Stage 
* [X] Player 
* [ ] Enemies
* [X] UI 

## Severity
Select the severity with and "x" ([x])

- [ ] **A** for crash 
- [X] **B** for game stopper 
- [ ] **C** for cosmetics 

## Steps to reproduce
Steps to follow:
- 1. Open the game and start stage 1
- 2. adquire a blue powerup for player 2
- 3. fire the charge laser (player 2)
- 4. player one score increases

## Conduct 
- Expected result: player 2 score adds while  player 2  is killing enemies
- Actual result: player 1 score goes up while player 2 is killing enemies

## Build
- Please specify the build:
 e4609ff

**Comment by DidacRomero** [comment]
This bug has been fixed! I proceed to close this issue.
