### ISSUE TITLE
Player 1 death while charging special attack won't allow to loose the game (no ships playing)

### ISSUE THREAD

**Issue by DidacRomero** [ch0m5/Project_1#4]
**Describe the bug**
When the Player 1 dies while his special attack is fully charged. If he dies BEFORE Player 2 and after that, Player 2 dies, there will be no fade to black to the loose screen.

## Type of Bug 

Select the type of bug with and "x" ([x])

* [ ] Art 
* [ ] Animation 
* [ ] Audio 
* [ ] Particles
* [ ] Stage 
* [x] Player 
* [ ] Enemies
* [ ] UI 

## Severity
Select the severity with and "x" ([x])

- [ ] **A** for crash 
- [x] **B** for game stopper 
- [ ] **C** for cosmetics 

**To Reproduce**
1. Open the game and start playing
2. Charge your attack to the maximum
3. Kill yourself until you loose all your lives as Player 1
4. Kill yourself until you loose all your lives as Player 2
...

## Conduct 
- **Expected result: There's a fade to black to the game over screen**
-  **Actual result: the map continues going forever without the players**

**Screenshots**

## Build
- **Please specify the build:** ``v.0.7 ``

**Additional context**

**Comment by ch0m5** [comment]
Thx for the feedback m8.
